### ISSUE TITLE
composer_home_path conditional fails in ansible 1.8

### ISSUE THREAD

**Issue by jrobeson** [kosssi/ansible-role-composer#14]
https://github.com/ansible/ansible/issues/9568

so the when statements need to be changed to check if the variable is defined.

I'll submit a PR to fix, if i get some status report on the PRs already submitted

**Comment by kosssi** [comment]
Hello @jrobeson 

I'm sorry for my silence, but I check this this week ;)

Thanks a lot

**Comment by kosssi** [comment]
The #15 is merged. Have you the same error ?

**Comment by jrobeson** [comment]
simply defining composer_home_path with a path is what breaks it:

i had to change:
when: composer_home_path
to 
when: composer_home_path is defined

**Comment by jrobeson** [comment]
ah, looks like you did get that. cool!
