### ISSUE TITLE
Configure github oauth token failed

### ISSUE THREAD

**Issue by iniweb** [kosssi/ansible-role-composer#19]
I used Vagrant + Ansible as provisioner, when i try to setup composer oAuth:

```
# vars/composer.yml
composer_github_oauth: 'mysupersecretkey'
```

Error:
```
TASK: [kosssi.composer | Configure composer path environment] *****************
skipping: [sf2]

TASK: [kosssi.composer | Global require packages] *****************************
skipping: [sf2]

TASK: [kosssi.composer | Configure github oauth token] ************************
failed: [sf2] => {"failed": true}
msg: Destination directory /root/.composer does not exist

FATAL: all hosts have already failed -- aborting
```

Even if i try to change

```
# vars/composer.yml
composer_github_oauth: 'mysupersecretkey'
composer_home_owner = vagrant
composer_home_group = vagrant
```

Vagrant 1.7.0
Ansible 1.9.0.1
kosssi.composer, v1.3.0 (installed by galaxy)

**Comment by kosssi** [comment]
Hello @iniweb 
I fix it this weekend but if you can make a PR it's beautiful :lollipop: 

Thanks for create this issue

**Comment by igormukhingmailcom** [comment]
Hi.

Fixed: https://github.com/kosssi/ansible-role-composer/pull/20

**Comment by kosssi** [comment]
@iniweb sorry for the delay but I am in holidays 😃
The new version v1.4.0 is for you.

Thanks @igormukhingmailcom

**Comment by iniweb** [comment]
Thanks guys, i just start digging in bug on weekends, but not finished... :) @igormukhingmailcom done better than i began  :+1:
