### ISSUE TITLE
Problems installing packages

### ISSUE THREAD

**Issue by markushausammann** [kosssi/ansible-role-composer#21]
I'm having troubles using this role, whatever I do I keep getting the error `with_dict expects a dict` when trying to use `composer_global_packages`. Can you maybe add an example of how this is used, the given example doesn't seem to be correct yaml syntax.

**Comment by markushausammann** [comment]
http://stackoverflow.com/questions/30475456/with-dict-expects-a-dict-ansible-global-composer-and-kosssi-composer

**Comment by kosssi** [comment]
Hello @markushausammann 

Have you a public repository ?
What is your version of Ansible ?
What is your version of the role ?

**Comment by markushausammann** [comment]
No public repository but see the stackoverflow question, latest Ansible, latest role version.

**Comment by kosssi** [comment]
what is latest Ansible, it's important.

**Comment by markushausammann** [comment]
As you can see from the SO answer, I just mixed up different yaml syntaxes.

**Comment by markushausammann** [comment]
The ansible version I use is 1.9.1.

**Comment by kosssi** [comment]
it's very not good idea to add variable like you do.

Create a file like that : https://github.com/Sharepear/ansible-playbook-sharepear/blob/master/vars/apt.yml
