### ISSUE TITLE
composer_github_oauth: false ends up in "None"

### ISSUE THREAD

**Issue by KingCrunch** [kosssi/ansible-role-composer#22]
I use

    composer_github_oauth: false

within `group_vars/all` and regarding the [condition within `tasks/oauth.yml`](https://github.com/kosssi/ansible-role-composer/blob/80b94b52ff194505766c7cf51dea6b799a5d51f3/tasks/oauth.yml#L7) I assumed, that this will disable the OAuth-token. But instead I get this in `~root/.composer/auth.json`

```yaml
{
    "github-oauth": {
        "github.com": "None"
    }
}
```
 Any idea?

**Comment by kosssi** [comment]
Hello @KingCrunch ,
Can you share your porvisioning ?

**Comment by KingCrunch** [comment]
OK, seems to be a differnet issue. I cannot reproduce it anymore... It seems the `None` came from somewhere else, but that showed me that `false` doesn't _update_ the `auth.json`

**Comment by kosssi** [comment]
I can close this issue ?
